### ISSUE TITLE
Unicode BOM sometimes causes parsing issues

### ISSUE THREAD

**Issue by davem2** [SpotlightKid/sfzparser#1]
Hi there,

First off thank you very much for sharing this code, its been very helpful with an SFZ conversion script I'm working on.

I came across an issue where the parser would miss the first section header on some sfz files causing the parser to fail with the error:

UnboundLocalError: local variable 'section_name' referenced before assignment

After some investigation I found that the problem files all used unicode BOM and had a section header on the first line of the file.  If the BOM is removed or a blank line is added to the head of the file, the file is processed as normal. I think whats happening the BOM is throwing off the section header regex (rx_section = re.compile('^<([^>]+)>\s?')) causing the section header on the first line to appear that its not at the start of the line.

An example .sfz which demonstrates the error can be found [here](https://www.dropbox.com/s/tmi0qsjxgs5bq9z/SnareandKick.sfz?dl=0)

**Comment by SpotlightKid** [comment]
Fixed with #2. Thanks Dave!
